-- begin TEACHINGSTUDENTS_GRADE_SHEET
alter table TEACHINGSTUDENTS_GRADE_SHEET add constraint FK_TEACHINGSTUDENTS_GRADE_SHEET_ON_UNIVERSITY_TEACHER foreign key (UNIVERSITY_TEACHER_ID) references TEACHINGSTUDENTS_UNIVERSITY_TEACHER(ID)^
create index IDX_TEACHINGSTUDENTS_GRADE_SHEET_ON_UNIVERSITY_TEACHER on TEACHINGSTUDENTS_GRADE_SHEET (UNIVERSITY_TEACHER_ID)^
-- end TEACHINGSTUDENTS_GRADE_SHEET
-- begin TEACHINGSTUDENTS_UNIVERSITY_TEACHER
create unique index IDX_TEACHINGSTUDENTS_UNIVERSITY_TEACHER_UNIQ_EMAIL on TEACHINGSTUDENTS_UNIVERSITY_TEACHER (EMAIL)^
-- end TEACHINGSTUDENTS_UNIVERSITY_TEACHER
-- begin TEACHINGSTUDENTS_STUDENT
create unique index IDX_TEACHINGSTUDENTS_STUDENT_UNIQ_EMAIL_ADDRESS on TEACHINGSTUDENTS_STUDENT (EMAIL_ADDRESS)^
-- end TEACHINGSTUDENTS_STUDENT
-- begin TEACHINGSTUDENTS_REPORT
alter table TEACHINGSTUDENTS_REPORT add constraint FK_TEACHINGSTUDENTS_REPORT_ON_TASK foreign key (TASK_ID) references TEACHINGSTUDENTS_TASK(ID)^
alter table TEACHINGSTUDENTS_REPORT add constraint FK_TEACHINGSTUDENTS_REPORT_ON_STUDENT foreign key (STUDENT_ID) references TEACHINGSTUDENTS_STUDENT(ID)^
create unique index IDX_TEACHINGSTUDENTS_REPORT_UNIQ_IDREPORT on TEACHINGSTUDENTS_REPORT (IDREPORT)^
create index IDX_TEACHINGSTUDENTS_REPORT_ON_TASK on TEACHINGSTUDENTS_REPORT (TASK_ID)^
create index IDX_TEACHINGSTUDENTS_REPORT_ON_STUDENT on TEACHINGSTUDENTS_REPORT (STUDENT_ID)^
-- end TEACHINGSTUDENTS_REPORT
-- begin TEACHINGSTUDENTS_TASK
alter table TEACHINGSTUDENTS_TASK add constraint FK_TEACHINGSTUDENTS_TASK_ON_PROFESSOR foreign key (PROFESSOR_ID) references TEACHINGSTUDENTS_UNIVERSITY_TEACHER(ID)^
create unique index IDX_TEACHINGSTUDENTS_TASK_UNIQ_IDTASK on TEACHINGSTUDENTS_TASK (IDTASK)^
create index IDX_TEACHINGSTUDENTS_TASK_ON_PROFESSOR on TEACHINGSTUDENTS_TASK (PROFESSOR_ID)^
-- end TEACHINGSTUDENTS_TASK
