alter table TEACHINGSTUDENTS_REPORT add constraint FK_TEACHINGSTUDENTS_REPORT_ON_TASK foreign key (TASK_ID) references TEACHINGSTUDENTS_TASK(ID);
alter table TEACHINGSTUDENTS_REPORT add constraint FK_TEACHINGSTUDENTS_REPORT_ON_STUDENT foreign key (STUDENT_ID) references TEACHINGSTUDENTS_STUDENT(ID);
create unique index IDX_TEACHINGSTUDENTS_REPORT_UNIQ_IDREPORT on TEACHINGSTUDENTS_REPORT (IDREPORT);
create index IDX_TEACHINGSTUDENTS_REPORT_ON_TASK on TEACHINGSTUDENTS_REPORT (TASK_ID);
create index IDX_TEACHINGSTUDENTS_REPORT_ON_STUDENT on TEACHINGSTUDENTS_REPORT (STUDENT_ID);
